### ISSUE TITLE
homepage kazakh painting!!!

### ISSUE THREAD

**Issue by Bubblent** [rendizi/nis-art-house#2]

**Comment by abglnv** [comment]
Where is the description??? What should we do??? @Bubblent

**Comment by Bubblent** [comment]
you got a book with paintings on your emails choose some paintngs

**Comment by Bubblent** [comment]
[image: image.png]

вт, 31 окт. 2023 г. в 14:49, Ayanat Islam ***@***.***>:

**Comment by Bubblent** [comment]
do you like it


вт, 31 окт. 2023 г. в 14:52, Ayanat Islam ***@***.***>:

**Comment by Bubblent** [comment]
finally i did it thanks to kerey
